name: flutter_audio_query
description: Flutter plugin to query data about artists, albums, songs, genres and playlists
  from device storage.
version: 0.3.3
author: Marcos Antonio Boaventura <scavenger.gnu@gmail.com>
homepage: https://github.com/sc4v3ng3r/flutter_audio_query

environment:
  sdk: ">=2.1.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


flutter:

  plugin:
    androidPackage: boaventura.com.devel.br.flutteraudioquery
    pluginClass: FlutterAudioQueryPlugin
